stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.url
      - data_ingestion.save_dir
    outs:
      - data/raw/reddit.csv

  data_clean:
    cmd: python3 src/data_cleaning.py
    deps:
      - src/data_cleaning.py
      - data/raw/reddit.csv
    outs:
      - data/processed/cleaned.csv

  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/cleaned.csv
    outs:
      - data/final/train.csv
      - data/final/test.csv
