stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.url
    outs:
      - data/raw/reddit.csv

  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/reddit.csv
    params:
      - data_preprocessing.keep_stop_words
      - data_preprocessing.test_size
      - data_preprocessing.random_state
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  feature_engineering:
    cmd: python3 src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - feature_engineering.ngram_range
      - feature_engineering.max_features
    outs:
      - data/final/train.csv
      - data/final/test.csv
      - models/transformer.pkl

  model_building:
    cmd: python3 src/model_building.py
    deps:
      - data/final/train.csv
      - data/final/test.csv
      - src/model_building.py
    params:
      - model_building.model_parameters

    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - data/final/train.csv
      - data/final/test.csv
      - models/tfidf_vectorizer.pkl
      - models/final_model.pkl
