data_ingestion:
  url: https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv

data_preprocessing:
  keep_stop_words:
    - not
    - however
    - although
    - but
  test_size: 0.2
  random_state: 42

feature_engineering:
  ngram_range:
    - 1
    - 3
  max_features: 1000





