name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGHUBS }}
        run: |
          pip install -r requirements.txt
          python3.10 -c "import nltk; nltk.download('stopwords')"
          python3.10 -c "import nltk; nltk.download('wordnet')"

      - name: run pipeline
        run: |
          dvc repro