name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          python3.10 -c "import nltk; nltk.download('stopwords')"
          python3.10 -c "import nltk; nltk.download('wordnet')"

      - name: run pipeline
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc repro
      - name: test run
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python3.10 -m unittest discover -s test -p "model_test.py"


      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes to Git
        run: |
          git add .

      - name: Commit changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        run: |
          git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"

      - name: Push changes
        if: ${{ github.actor != 'github-actions[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ github.ref_name }}