name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "DAGSHUB_TOKEN is set"
          pip install -r requirements.txt
          python3.10 -c "import nltk; nltk.download('stopwords')"
          python3.10 -c "import nltk; nltk.download('wordnet')"

      - name: Print environment variables
        run: env

      - name: run pipeline
        run: |
          dvc repro
