name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          python3.10 -c "import nltk; nltk.download('stopwords')"
          python3.10 -c "import nltk; nltk.download('wordnet')"

      - name: run pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc repro
      - name: test run
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python3.10 -m unittest discover -s test 
